# Generated by Django 5.2 on 2025-04-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='Habilidades',
            field=models.ManyToManyField(to='empleado.habilidades'),
        ),
    ]
